<?php

/**
 * @file
 * Provides a radio widget for EC product variation selection.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function ec_radio_widget_theme(): array {
  return [
    'form_element__radio__product_variation_radio' => [
      'render element' => 'element',
      'base hook' => 'form_element',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_form_element_alter().
 */
function ec_radio_widget_theme_suggestions_form_element_alter(array &$suggestions, array $variables): void {
  $element = $variables['element'];

  if (isset($element['#type']) && isset($element['#context']['widget'])) {
    $suggestions[] = 'form_element__' . str_replace('-', '_', $element['#type']) . '__product_variation_radio';
  }
}

/**
 * Implements hook_form_alter().
 */
function ec_radio_widget_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  $forms = [
    '_add_cart_form_',
    '_add_to_cart_form_',
  ];

  if (!array_filter($forms, fn($prefix) => str_contains($form_id, $prefix)) || isset($form['quantity'])) {
    return;
  }

  $form['quantity'] = [
    '#type' => 'hidden',
    '#value' => 1,
    '#default_value' => 1,
  ];
}
